import { FindManyDiplomeArgs, FindUniqueDiplomeArgs } from './dtos/find.args';
import { PrismaService } from 'src/common/prisma/prisma.service';
import { CreateDiplomeInput } from './dtos/create-diplome.input';
import { UpdateDiplomeInput } from './dtos/update-diplome.input';
import { Prisma } from '@prisma/client';
export declare class DiplomesService {
    private readonly prisma;
    constructor(prisma: PrismaService);
    create(createDiplomeInput: CreateDiplomeInput): Prisma.Prisma__DiplomeClient<{
        id: number;
        createdAt: Date;
        updatedAt: Date;
        nom: string;
        finalite: string;
        entite: string;
        habilitation: string;
        partenaires: string[];
        dateCreation: Date;
        dateHabilitation: Date;
        dateEcheance: Date;
        duree: number;
        specialiteId: number;
    }, never, import("@prisma/client/runtime/library").DefaultArgs>;
    findAll(args: FindManyDiplomeArgs): Prisma.PrismaPromise<{
        id: number;
        createdAt: Date;
        updatedAt: Date;
        nom: string;
        finalite: string;
        entite: string;
        habilitation: string;
        partenaires: string[];
        dateCreation: Date;
        dateHabilitation: Date;
        dateEcheance: Date;
        duree: number;
        specialiteId: number;
    }[]>;
    findAllByEtablissement(args: FindManyDiplomeArgs, etablissementId: number): Prisma.PrismaPromise<{
        id: number;
        createdAt: Date;
        updatedAt: Date;
        nom: string;
        finalite: string;
        entite: string;
        habilitation: string;
        partenaires: string[];
        dateCreation: Date;
        dateHabilitation: Date;
        dateEcheance: Date;
        duree: number;
        specialiteId: number;
    }[]>;
    findOne(args: FindUniqueDiplomeArgs): Prisma.Prisma__DiplomeClient<{
        id: number;
        createdAt: Date;
        updatedAt: Date;
        nom: string;
        finalite: string;
        entite: string;
        habilitation: string;
        partenaires: string[];
        dateCreation: Date;
        dateHabilitation: Date;
        dateEcheance: Date;
        duree: number;
        specialiteId: number;
    }, null, import("@prisma/client/runtime/library").DefaultArgs>;
    update(updateDiplomeInput: UpdateDiplomeInput): Prisma.Prisma__DiplomeClient<{
        id: number;
        createdAt: Date;
        updatedAt: Date;
        nom: string;
        finalite: string;
        entite: string;
        habilitation: string;
        partenaires: string[];
        dateCreation: Date;
        dateHabilitation: Date;
        dateEcheance: Date;
        duree: number;
        specialiteId: number;
    }, never, import("@prisma/client/runtime/library").DefaultArgs>;
    remove(args: FindUniqueDiplomeArgs): Prisma.Prisma__DiplomeClient<{
        id: number;
        createdAt: Date;
        updatedAt: Date;
        nom: string;
        finalite: string;
        entite: string;
        habilitation: string;
        partenaires: string[];
        dateCreation: Date;
        dateHabilitation: Date;
        dateEcheance: Date;
        duree: number;
        specialiteId: number;
    }, never, import("@prisma/client/runtime/library").DefaultArgs>;
}
