// ueData.ts
export const ueData = [
  // LICENCE COMPTABILITÉ ET GESTION FINANCIÈRE (CGF) - L1 Semestre 1 (Classe L1 CG)
  {
    code: '111',
    nom: 'TECHNIQUES QUANTITATIVES DE GESTION',
    semestre: 1,
    classeCode: 'L1 CG',
    numero: 1,
    credit: 6,
    matieres: [
      {
        code: '1111',
        nom: 'Comptabilité générale 1',
        credit: 4,
        coefficient: 6,
      },
      {
        code: '1112',
        nom: 'Mathélatiques financières 1',
        credit: 2,
        coefficient: 3,
      },
    ],
  },
  {
    code: '112',
    nom: 'OUTILS MATHEMATIQUES DE GESTION',
    semestre: 1,
    classeCode: 'L1 CG',
    numero: 2,
    credit: 6,
    matieres: [
      {
        code: '1121',
        nom: 'Mathématiques générales 1',
        credit: 4,
        coefficient: 6,
      },
      {
        code: '1122',
        nom: 'Statistique descriptive 1',
        credit: 2,
        coefficient: 2,
      },
    ],
  },
  {
    code: '113',
    nom: "ENVIRONNEMENT ECONOMIQUE ET JURIDIQUE",
    semestre: 1,
    classeCode: 'L1 CG',
    numero: 3,
    credit: 6,
    matieres: [
      {
        code: '1131',
        nom: 'Micro - économie',
        credit: 2,
        coefficient: 6,
      },
      {
        code: '1132',
        nom: 'Introduction au droit',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '1133',
        nom: "Economie d'entreprise",
        credit: 2,
        coefficient: 2,
      },
    ],
  },
  {
    code: '114',
    nom: 'STRATEGIE ET COMMUNICATION',
    semestre: 1,
    classeCode: 'L1 CG',
    numero: 4,
    credit: 6,
    matieres: [
      {
        code: '1141',
        nom: 'Introduction au marketing',
        credit: 2,
        coefficient: 6,
      },
      {
        code: '1142',
        nom: 'Techniques d\'expression francaise 1',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '1143',
        nom: 'Théorie des organisations',
        credit: 2,
        coefficient: 2,
      },
    ],
  },
  {
    code: '115',
    nom: 'OUTILS DE COMMUNICATION',
    semestre: 1,
    classeCode: 'L1 CG',
    numero: 5,
    credit: 6,
    matieres: [
      {
        code: '1151',
        nom: 'Informatique ( Traitement de textes Word)',
        credit: 2,
        coefficient: 6,
      },
      {
        code: '1152',
        nom: 'Développement personnel',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '1153',
        nom: 'Anglais des affaires 1',
        credit: 3,
        coefficient: 2,
      },
    ],
  },

  // LICENCE COMPTABILITÉ ET GESTION FINANCIÈRE (CGF) - L2 Semestre 3 (Classe L2 CG)
  {
    code: '231',
    nom: 'TECHNIQUES QUANTITATIVES DE GESTION',
    semestre: 3,
    classeCode: 'L2 CG',
    numero: 1,
    credit: 0, // valeurs dans fichier à 0
    matieres: [
      {
        code: '2311',
        nom: 'Comptabilité analytique',
        credit: 3,
        coefficient: 4,
      },
      {
        code: '2312',
        nom: 'Comptabilité des sociétés 1',
        credit: 3,
        coefficient: 3,
      },
    ],
  },
  {
    code: '232',
    nom: 'OUTILS MATHEMATIQUES DE GESTION',
    semestre: 3,
    classeCode: 'L2 CG',
    numero: 2,
    credit: 0,
    matieres: [
      {
        code: '2321',
        nom: 'Mathématiques générales (analyse)',
        credit: 3,
        coefficient: 3,
      },
      {
        code: '2322',
        nom: 'Probabilités - statistiques',
        credit: 3,
        coefficient: 2,
      },
    ],
  },
  {
    code: '233',
    nom: 'ENVIRONNEMENT ECONOMIQUE ET FINANCIER DES AFFAIRES',
    semestre: 3,
    classeCode: 'L2 CG',
    numero: 3,
    credit: 0,
    matieres: [
      {
        code: '2331',
        nom: 'Fiscalité 2',
        credit: 3,
        coefficient: 2,
      },
      {
        code: '2332',
        nom: 'Economie internationale',
        credit: 1,
        coefficient: 2,
      },
      {
        code: '2333',
        nom: 'Droit du travail et de la sécurité sociale',
        credit: 2,
        coefficient: 1,
      },
    ],
  },
  {
    code: '234',
    nom: 'PRATIQUE PROFESSIONNELLE',
    semestre: 3,
    classeCode: 'L2 CG',
    numero: 4,
    credit: 0,
    matieres: [
      {
        code: '2341',
        nom: 'Gestion de projet',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '2342',
        nom: "Techiques de recherche d'emploi",
        credit: 2,
        coefficient: 2,
      },
      {
        code: '2343',
        nom: 'Leadership et coaching',
        credit: 2,
        coefficient: 2,
      },
    ],
  },
  {
    code: '235',
    nom: 'OUTILS DE COMMUNICATION',
    semestre: 3,
    classeCode: 'L2 CG',
    numero: 5,
    credit: 0,
    matieres: [
      {
        code: '2351',
        nom: 'Informatique Tableur Excel',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '2352',
        nom: 'Anglais des affaires 3',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '2353',
        nom: 'Bases de données',
        credit: 2,
        coefficient: 2,
      },
    ],
  },

  // LICENCE COMPTABILITÉ ET GESTION FINANCIÈRE (CGF) - L3 Semestre 5 (Classe L3 CG)
  {
    code: '351',
    nom: 'TECHNIQUES QUANTITATIVES DE GESTION',
    semestre: 5,
    classeCode: 'L3 CG',
    numero: 1,
    credit: 0,
    matieres: [
      {
        code: '3511',
        nom: 'Comptabilité générale approfondie',
        credit: 4,
        coefficient: 4,
      },
      {
        code: '3512',
        nom: "Contrôle de gestion et pilotage de l'entreprise",
        credit: 2,
        coefficient: 3,
      },
    ],
  },
  {
    code: '352',
    nom: 'MANAGEMENT ET STRATEGIE',
    semestre: 5,
    classeCode: 'L3 CG',
    numero: 2,
    credit: 0,
    matieres: [
      {
        code: '3521',
        nom: 'Management des ressources humaines',
        credit: 3,
        coefficient: 2,
      },
      {
        code: '3522',
        nom: 'Management de la qualité',
        credit: 3,
        coefficient: 2,
      },
    ],
  },
  {
    code: '353',
    nom: 'ENVIRONNEMENT ECONOMIQUE ET FINANCIER DES AFFAIRES',
    semestre: 5,
    classeCode: 'L3 CG',
    numero: 3,
    credit: 0,
    matieres: [
      {
        code: '3531',
        nom: 'Politique monétaire',
        credit: 3,
        coefficient: 2,
      },
      {
        code: '3532',
        nom: 'Marchés financiers',
        credit: 3,
        coefficient: 2,
      },
    ],
  },
  {
    code: '354',
    nom: 'MANAGEMENT',
    semestre: 5,
    classeCode: 'L3 CG',
    numero: 4,
    credit: 0,
    matieres: [
      {
        code: '3541',
        nom: 'Gestion budgétaire',
        credit: 3,
        coefficient: 1,
      },
      {
        code: '3542',
        nom: 'Gestion de portefeuilles clients',
        credit: 3,
        coefficient: 2,
      },
    ],
  },
  {
    code: '355',
    nom: 'OUTILS DE PROFESSIONNALISATION',
    semestre: 5,
    classeCode: 'L3 CG',
    numero: 5,
    credit: 0,
    matieres: [
      {
        code: '3551',
        nom: 'informatique (Logiciel intégré de gestion)',
        credit: 3,
        coefficient: 1,
      },
      {
        code: '3552',
        nom: 'Entrepreneuriat',
        credit: 3,
        coefficient: 1,
      },
    ],
  },

  // LICENCE MARKETING - L1 Semestre 1 (Classe L1 MK)
  {
    code: '111',
    nom: 'OUTILS DE GESTION COMMERCIALE',
    semestre: 1,
    classeCode: 'L1 MK',
    numero: 1,
    credit: 0,
    matieres: [
      {
        code: '1111',
        nom: 'Comptabilité générale 1',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '1112',
        nom: 'Mathématiques financières 1',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '1113',
        nom: 'Statistiques descriptives 1',
        credit: 2,
        coefficient: 2,
      },
    ],
  },
  {
    code: '112',
    nom: 'MARKETING ET MANAGEMENT',
    semestre: 1,
    classeCode: 'L1 MK',
    numero: 2,
    credit: 0,
    matieres: [
      {
        code: '1121',
        nom: 'Introduction au marketing',
        credit: 4,
        coefficient: 4,
      },
      {
        code: '1122',
        nom: 'Théorie des organisations',
        credit: 2,
        coefficient: 2,
      },
    ],
  },
  {
    code: '113',
    nom: 'ENVIRONNEMENT ECONOMIQUE ET JURIDIQUE',
    semestre: 1,
    classeCode: 'L1 MK',
    numero: 3,
    credit: 0,
    matieres: [
      {
        code: '1131',
        nom: 'Economie Générale 1',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '1132',
        nom: 'Droit civil',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '1133',
        nom: "Economie d'entreprise 1",
        credit: 3,
        coefficient: 2,
      },
    ],
  },
  {
    code: '114',
    nom: 'FONDEMENT ET ETCHNIQUES DE COMMUNICATION',
    semestre: 1,
    classeCode: 'L1 MK',
    numero: 4,
    credit: 0,
    matieres: [
      {
        code: '1141',
        nom: 'Fondements de la communication',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '1142',
        nom: 'techniques de communication',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '1143',
        nom: 'Techniques d\'expression francaise 1',
        credit: 2,
        coefficient: 2,
      },
    ],
  },
  {
    code: '115',
    nom: 'OUTILS DE DEVELOPPEMENT PERSONNEL',
    semestre: 1,
    classeCode: 'L1 MK',
    numero: 5,
    credit: 6,
    matieres: [
      {
        code: '1151',
        nom: 'informatique Word',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '1152',
        nom: 'Développement personnel et professionnel',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '1153',
        nom: 'Anglais des affaires 1',
        credit: 2,
        coefficient: 2,
      },
    ],
  },

  // LICENCE MARKETING - L2 Semestre 3 (Classe L2 MK)
  {
    code: '231',
    nom: 'OUTILS DE GESTION COMMERCIALE',
    semestre: 3,
    classeCode: 'L2 MK',
    numero: 1,
    credit: 0,
    matieres: [
      {
        code: '2311',
        nom: 'Analyse comptable',
        credit: 3,
        coefficient: 4,
      },
      {
        code: '2312',
        nom: 'Statistiques inferentielles',
        credit: 3,
        coefficient: 3,
      },
    ],
  },
  {
    code: '232',
    nom: 'STRATEGIE ET TACTIQUE DU MARKETING',
    semestre: 3,
    classeCode: 'L2 MK',
    numero: 2,
    credit: 0,
    matieres: [
      {
        code: '2321',
        nom: 'Marketing stratégique',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '2322',
        nom: 'Mix Marketing',
        credit: 2,
        coefficient: 3,
      },
      {
        code: '2323',
        nom: 'merchandising',
        credit: 2,
        coefficient: 3,
      },
    ],
  },
  {
    code: '233',
    nom: 'DROIT - PRATIQUE DU COMMERCE INTERNATIONAL ET DU NUMERIQUE',
    semestre: 3,
    classeCode: 'L2 MK',
    numero: 3,
    credit: 0,
    matieres: [
      {
        code: '2331',
        nom: 'Droit du travail et de la sécurité sociale',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '2332',
        nom: 'Techniques du commerce international',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '2333',
        nom: 'Droit du E-Commerce',
        credit: 2,
        coefficient: 1,
      },
    ],
  },
  {
    code: '234',
    nom: 'PRATIQUE PROFESSIONNELLE',
    semestre: 3,
    classeCode: 'L2 MK',
    numero: 4,
    credit: 0,
    matieres: [
      {
        code: '2341',
        nom: 'Gestion de projet',
        credit: 2,
        coefficient: 3,
      },
      {
        code: '2342',
        nom: 'Méthodologie de rédaction action commerciale',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '2343',
        nom: 'Réalisation de dossiers commerciaux',
        credit: 2,
        coefficient: 2,
      },
    ],
  },
  {
    code: '235',
    nom: 'LANGUES ET OUTILS DE COMMUNICATION',
    semestre: 3,
    classeCode: 'L2 MK',
    numero: 5,
    credit: 0,
    matieres: [
      {
        code: '2451',
        nom: 'informatique Excel - Tableaux de bord comm',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '2352',
        nom: 'Anglais des affaires 3',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '2353',
        nom: 'Bases de données',
        credit: 2,
        coefficient: 2,
      },
    ],
  },

  // LICENCE MARKETING - L3 Semestre 5 (Classe L3 MK)
  {
    code: '351',
    nom: 'MARKETING INDUSTRIEL ET GESTION COMMERCIALE',
    semestre: 5,
    classeCode: 'L3 MK',
    numero: 1,
    credit: 0,
    matieres: [
      {
        code: '3511',
        nom: 'Marketing industriel B to B',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '3512',
        nom: 'Logiciel de gestion commerciale',
        credit: 2,
        coefficient: 3,
      },
      {
        code: '3513',
        nom: 'Gestion des stocks',
        credit: 2,
        coefficient: 2,
      },
    ],
  },
  {
    code: '352',
    nom: 'ENVIRONNEMENT ECONOMIQUE ET FINANCIER DES AFFAIRES',
    semestre: 5,
    classeCode: 'L3 MK',
    numero: 2,
    credit: 0,
    matieres: [
      {
        code: '3521',
        nom: 'Droit des affaires',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '3522',
        nom: 'Achats et approvisionnement',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '3523',
        nom: 'Entrepreneuriat',
        credit: 2,
        coefficient: 2,
      },
    ],
  },
  {
    code: '353',
    nom: 'CREATION ET CONCEPTION DE CONTENUS',
    semestre: 5,
    classeCode: 'L3 MK',
    numero: 3,
    credit: 0,
    matieres: [
      {
        code: '3531',
        nom: 'Infographie',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '3532',
        nom: 'Création de sites web',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '3533',
        nom: 'Multimédia',
        credit: 2,
        coefficient: 2,
      },
    ],
  },
  {
    code: '354',
    nom: 'PUBLICITE ET MEDIA',
    semestre: 5,
    classeCode: 'L3 MK',
    numero: 4,
    credit: 0,
    matieres: [
      {
        code: '3541',
        nom: 'Communication et actions publicitaires',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '3542',
        nom: 'Stratégie des marques',
        credit: 2,
        coefficient: 2,
      },
    ],
  },
  {
    code: '355',
    nom: 'PROJET TUTORE',
    semestre: 5,
    classeCode: 'L3 MK',
    numero: 5,
    credit: 0,
    matieres: [
      {
        code: '3551',
        nom: 'Méthodologie de recherche',
        credit: 4,
        coefficient: 2,
      },
      {
        code: '3552',
        nom: 'Adapatation au milieu du travail',
        credit: 4,
        coefficient: 2,
      },
    ],
  },
  // LICENCE COMPTABILITÉ ET GESTION FINANCIÈRE (CGF)

  // LICENCE COMPTABILITÉ ET GESTION FINANCIÈRE (CGF) - L1 Semestre 2 (Classe L1 CG)
  {
    code: '121',
    nom: 'TECHNIQUES QUANTITATIVES DE GESTION',
    semestre: 2,
    classeCode: 'L1 CG',
    numero: 1,
    credit: 6,
    matieres: [
      {
        code: '1211',
        nom: 'Comptabilité générale 2',
        credit: 4,
        coefficient: 4,
      },
      {
        code: '1212',
        nom: 'Mathématiques financières 2',
        credit: 2,
        coefficient: 2,
      },
    ],
  },
  {
    code: '122',
    nom: 'OUTILS MATHEMATIQUES DE GESTION',
    semestre: 2,
    classeCode: 'L1 CG',
    numero: 2,
    credit: 6,
    matieres: [
      {
        code: '1221',
        nom: 'Mathématiques générales 2',
        credit: 4,
        coefficient: 3,
      },
      {
        code: '1222',
        nom: 'Statistique descriptive 2',
        credit: 2,
        coefficient: 2,
      },
    ],
  },
  {
    code: '123',
    nom: 'ENVIRONNEMENT ECONOMIQUE ET JURIDIQUE',
    semestre: 2,
    classeCode: 'L1 CG',
    numero: 3,
    credit: 6,
    matieres: [
      {
        code: '1231',
        nom: 'Fiscalité 2',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '1232',
        nom: 'Droit commercial',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '1233',
        nom: 'Macro-économie (comptabilité nationale)',
        credit: 2,
        coefficient: 2,
      },
    ],
  },
  {
    code: '124',
    nom: 'STRATEGIE ET COMMUNICATION',
    semestre: 2,
    classeCode: 'L1 CG',
    numero: 4,
    credit: 6,
    matieres: [
      {
        code: '1241',
        nom: 'Marketing 2',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '1242',
        nom: 'Initiation au management',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '1243',
        nom: 'Sociologie des organisations',
        credit: 2,
        coefficient: 2,
      },
    ],
  },
  {
    code: '125',
    nom: 'OUTILS DE COMMUNICATION',
    semestre: 2,
    classeCode: 'L1 CG',
    numero: 5,
    credit: 6,
    matieres: [
      {
        code: '1251',
        nom: 'Informatique Tableur Excel',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '1252',
        nom: 'Techniques de communication',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '1253',
        nom: 'Anglais des affaires 2',
        credit: 2,
        coefficient: 2,
      },
    ],
  },

  // LICENCE COMPTABILITÉ ET GESTION FINANCIÈRE (CGF) - L2 Semestre 4 (Classe L2 CG)
  {
    code: '241',
    nom: 'TECHNIQUES QUANTITATIVES DE GESTION',
    semestre: 4,
    classeCode: 'L2 CG',
    numero: 1,
    credit: 6,
    matieres: [
      {
        code: '2411',
        nom: 'Comptabilité analytique 2',
        credit: 3,
        coefficient: 4,
      },
      {
        code: '2412',
        nom: 'Comptabilité des sociétés 2',
        credit: 3,
        coefficient: 3,
      },
    ],
  },
  {
    code: '242',
    nom: 'OUTILS MATHEMATIQUES DE GESTION',
    semestre: 4,
    classeCode: 'L2 CG',
    numero: 2,
    credit: 5,
    matieres: [
      {
        code: '2421',
        nom: 'Mathématiques générales 4',
        credit: 3,
        coefficient: 3,
      },
      {
        code: '2422',
        nom: 'Probabilités - statistiques',
        credit: 2,
        coefficient: 2,
      },
    ],
  },
  {
    code: '243',
    nom: "ENVIRONNEMENT ECONOMIQUE ET FINANCIER DES AFFAIRES",
    semestre: 4,
    classeCode: 'L2 CG',
    numero: 3,
    credit: 5,
    matieres: [
      {
        code: '2431',
        nom: "Financement de l'entreprise",
        credit: 2,
        coefficient: 2,
      },
      {
        code: '2432',
        nom: 'Finance internationale',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '2433',
        nom: 'Marché des capitaux',
        credit: 1,
        coefficient: 1,
      },
    ],
  },
  {
    code: '244',
    nom: 'PRATIQUE PROFESSIONNELLE',
    semestre: 4,
    classeCode: 'L2 CG',
    numero: 4,
    credit: 4,
    matieres: [
      {
        code: '2441',
        nom: 'Travaux de synthèse',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '2442',
        nom: 'Bureau d\'adaptation au monde du travail',
        credit: 2,
        coefficient: 2,
      },
    ],
  },
  {
    code: '245',
    nom: 'OUTILS DE COMMUNICATION',
    semestre: 4,
    classeCode: 'L2 CG',
    numero: 5,
    credit: 5,
    matieres: [
      {
        code: '2451',
        nom: 'Informatique (Powerpoint)',
        credit: 1,
        coefficient: 1,
      },
      {
        code: '2452',
        nom: 'Anglais des affaires 4',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '2453',
        nom: 'Pratique de Saari Compta',
        credit: 2,
        coefficient: 2,
      },
    ],
  },
  {
    code: '246',
    nom: 'PROJET TUTORE',
    semestre: 4,
    classeCode: 'L2 CG',
    numero: 6,
    credit: 0,
    matieres: [
      {
        code: '2461',
        nom: 'Méthodologie de rédaction rapport de stage',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '2462',
        nom: 'Stage ou immersion en entreprise',
        credit: 3,
        coefficient: 3,
      },
    ],
  },

  // LICENCE COMPTABILITÉ ET GESTION FINANCIÈRE (CGF) - L3 Semestre 6 (Classe L3 CG)
  {
    code: '361',
    nom: 'DECISIONS ET POLITIQUE FINANCIERE',
    semestre: 6,
    classeCode: 'L3 CG',
    numero: 1,
    credit: 6,
    matieres: [
      {
        code: '3611',
        nom: 'Gestion financière',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '3612',
        nom: 'Révisions comptables',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '3613',
        nom: 'Gestion de la trésorerie',
        credit: 2,
        coefficient: 2,
      },
    ],
  },
  {
    code: '362',
    nom: 'COMPTABILITES SPECIFIQUES',
    semestre: 6,
    classeCode: 'L3 CG',
    numero: 2,
    credit: 6,
    matieres: [
      {
        code: '3621',
        nom: 'Comptabilité bancaire',
        credit: 3,
        coefficient: 2,
      },
      {
        code: '3622',
        nom: 'Comptabilité des assurances',
        credit: 3,
        coefficient: 2,
      },
    ],
  },
  {
    code: '363',
    nom: 'ORGANISATION ET REGLEMENTATION',
    semestre: 6,
    classeCode: 'L3 CG',
    numero: 3,
    credit: 6,
    matieres: [
      {
        code: '3631',
        nom: 'Audit interne et gestion des risques',
        credit: 3,
        coefficient: 2,
      },
      {
        code: '3632',
        nom: 'Comptabilité des assurances',
        credit: 3,
        coefficient: 2,
      },
    ],
  },
  {
    code: '364',
    nom: 'PROJET TUTORE',
    semestre: 6,
    classeCode: 'L3 CG',
    numero: 4,
    credit: 7,
    matieres: [
      {
        code: '3641',
        nom: 'Stage',
        credit: 5,
        coefficient: 1,
      },
      {
        code: '3642',
        nom: 'Méthodologie de rédaction de mémoire',
        credit: 2,
        coefficient: 1,
      },
      {
        code: '3643',
        nom: 'Soutenance rapport / mémoire',
        credit: 5,
        coefficient: 3,
      },
    ],
  },

  // LICENCE MARKETING

  // LICENCE MARKETING - L1 Semestre 2 (Classe L1 MK)
  {
    code: '121',
    nom: 'OUTILS DE GESTION COMMERCIALE',
    semestre: 2,
    classeCode: 'L1 MK',
    numero: 1,
    credit: 30,
    matieres: [
      {
        code: '1211',
        nom: 'Comptabilité générale 2',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '1212',
        nom: 'Mathématiques financières 2',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '1213',
        nom: 'Statistique descriptive 2',
        credit: 2,
        coefficient: 2,
      },
    ],
  },
  {
    code: '122',
    nom: 'STRATEGIE MARKETING',
    semestre: 2,
    classeCode: 'L1 MK',
    numero: 2,
    credit: 8,
    matieres: [
      {
        code: '1221',
        nom: 'Orientation stratégique',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '1222',
        nom: 'Comportement du consommateur',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '1223',
        nom: 'Etude et analyse de marché',
        credit: 4,
        coefficient: 3,
      },
    ],
  },
  {
    code: '123',
    nom: 'ENVIRONNEMENT ECONOMIQUE ET JURIDIQUE',
    semestre: 2,
    classeCode: 'L1 MK',
    numero: 3,
    credit: 6,
    matieres: [
      {
        code: '1231',
        nom: 'Economie générale 2',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '1232',
        nom: 'Droit commercial',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '1233',
        nom: 'Economie d\'entreprise 2',
        credit: 2,
        coefficient: 3,
      },
    ],
  },
  {
    code: '124',
    nom: 'ETHIQUE ET RSE',
    semestre: 2,
    classeCode: 'L1 MK',
    numero: 4,
    credit: 4,
    matieres: [
      {
        code: '1241',
        nom: 'Communication éthique',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '1242',
        nom: 'Marketing durable',
        credit: 1,
        coefficient: 2,
      },
      {
        code: '1243',
        nom: 'Stratégie RSE',
        credit: 1,
        coefficient: 2,
      },
    ],
  },
  {
    code: '125',
    nom: 'LANGUES ET OUTILS DE COMMUNICATION',
    semestre: 2,
    classeCode: 'L1 MK',
    numero: 5,
    credit: 6,
    matieres: [
      {
        code: '1251',
        nom: 'Informatique (Tableur Excel)',
        credit: 3,
        coefficient: 2,
      },
      {
        code: '1252',
        nom: 'Anglais des affaires 2',
        credit: 3,
        coefficient: 2,
      },
    ],
  },

  // LICENCE MARKETING - L2 Semestre 4 (Classe L2 MK)
  {
    code: '241',
    nom: 'OUTILS DE GESTION COMMERCIALE',
    semestre: 4,
    classeCode: 'L2 MK',
    numero: 1,
    credit: 6,
    matieres: [
      {
        code: '2411',
        nom: 'Gestion budgétaire',
        credit: 3,
        coefficient: 4,
      },
      {
        code: '2412',
        nom: 'Analyse financière',
        credit: 3,
        coefficient: 3,
      },
    ],
  },
  {
    code: '242',
    nom: 'STRATEGIE COMMERCIALE GLOBALE',
    semestre: 4,
    classeCode: 'L2 MK',
    numero: 2,
    credit: 5,
    matieres: [
      {
        code: '2421',
        nom: 'Marketing international',
        credit: 1,
        coefficient: 2,
      },
      {
        code: '2422',
        nom: 'Négociation commerciale',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '2423',
        nom: 'Marketing expérientiel',
        credit: 2,
        coefficient: 2,
      },
    ],
  },
  {
    code: '243',
    nom: 'COMPORTEMENT HUMAIN ET GESTION DES TALENTS',
    semestre: 4,
    classeCode: 'L2 MK',
    numero: 3,
    credit: 5,
    matieres: [
      {
        code: '2431',
        nom: 'Management',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '2432',
        nom: 'Gestion des ressources humaines',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '2433',
        nom: 'Psychologie des organisations',
        credit: 1,
        coefficient: 1,
      },
    ],
  },
  {
    code: '244',
    nom: 'PRATIQUE PROFESSIONNELLE',
    semestre: 4,
    classeCode: 'L2 MK',
    numero: 4,
    credit: 6,
    matieres: [
      {
        code: '2441',
        nom: "Techniques de recherche d'emploi",
        credit: 2,
        coefficient: 2,
      },
      {
        code: '2442',
        nom: 'Réalisation de dossier d\'action commerciale',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '2443',
        nom: 'Travaux de synthèse',
        credit: 2,
        coefficient: 2,
      },
    ],
  },
  {
    code: '245',
    nom: 'INFORMATIQUE ET OUTILS D\'ANALYSE',
    semestre: 4,
    classeCode: 'L2 MK',
    numero: 5,
    credit: 3,
    matieres: [
      {
        code: '2451',
        nom: 'Informatique appliquée',
        credit: 1,
        coefficient: 1,
      },
      {
        code: '2452',
        nom: 'Analyse et traitement de données sous Sphinx',
        credit: 2,
        coefficient: 2,
      },
    ],
  },
  {
    code: '246',
    nom: 'PROJET TUTORE',
    semestre: 4,
    classeCode: 'L2 MK',
    numero: 6,
    credit: 5,
    matieres: [
      {
        code: '2461',
        nom: 'Méthodologie de rédaction rapport stage',
        credit: 2,
        coefficient: 1,
      },
      {
        code: '2462',
        nom: 'Stage ou immersion en entreprise',
        credit: 3,
        coefficient: 1,
      },
    ],
  },

  // LICENCE MARKETING - L3 Semestre 6 (Classe L3 MK)
  {
    code: '361',
    nom: 'GESTION STRATEGIQUE ET COMMUNICATION',
    semestre: 6,
    classeCode: 'L3 MK',
    numero: 1,
    credit: 6,
    matieres: [
      {
        code: '3611',
        nom: 'Etudes de cas de synthèse',
        credit: 2,
        coefficient: 3,
      },
      {
        code: '3612',
        nom: 'Stratégies et plans de communication',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '3613',
        nom: 'Audit marketing et planification stratégique',
        credit: 2,
        coefficient: 2,
      },
    ],
  },
  {
    code: '362',
    nom: 'LOGISTIQUE COMMERCIALE ET DROIT DES TRANSACTIONS',
    semestre: 6,
    classeCode: 'L3 MK',
    numero: 2,
    credit: 6,
    matieres: [
      {
        code: '3621',
        nom: 'Techniques de vente',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '3622',
        nom: 'Gestion des stocks',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '3623',
        nom: 'Droit de la consommation et de la concurrence',
        credit: 2,
        coefficient: 2,
      },
    ],
  },
  {
    code: '363',
    nom: 'TECHNIQUES NUMERIQUES',
    semestre: 6,
    classeCode: 'L3 MK',
    numero: 3,
    credit: 6,
    matieres: [
      {
        code: '3631',
        nom: 'Marketing digital',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '3632',
        nom: 'Communication digitale',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '3633',
        nom: 'Stratégie E-commerce',
        credit: 2,
        coefficient: 2,
      },
    ],
  },
  {
    code: '364',
    nom: 'COMMUNICATION STRATEGIQUE',
    semestre: 6,
    classeCode: 'L3 MK',
    numero: 4,
    credit: 4,
    matieres: [
      {
        code: '3641',
        nom: 'Communication de crise',
        credit: 2,
        coefficient: 2,
      },
      {
        code: '3642',
        nom: 'Communication institutionnelle',
        credit: 2,
        coefficient: 2,
      },
    ],
  },
  {
    code: '365',
    nom: 'PROJET TUTORE',
    semestre: 6,
    classeCode: 'L3 MK',
    numero: 5,
    credit: 8,
    matieres: [
      {
        code: '3651',
        nom: 'Méthodologie de rédaction mémoire / rapport',
        credit: 3,
        coefficient: 2,
      },
      {
        code: '3652',
        nom: 'Soutenance mémoire / rapport',
        credit: 5,
        coefficient: 4,
      },
    ],
  },
];