version: "3.8"
services:
  keycloak:
    image: jboss/keycloak
    ports:
      - 3344:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    volumes:
      - ./data/keycloak:/opt/jboss/keycloak/standalone/data
