import { FindManyCoursArgs, FindUniqueCoursArgs } from './dtos/find.args';
import { PrismaService } from 'src/common/prisma/prisma.service';
import { CreateCoursInput } from './dtos/create-cours.input';
import { UpdateCoursInput } from './dtos/update-cours.input';
import { Prisma } from '@prisma/client';
export declare class CoursService {
    private readonly prisma;
    constructor(prisma: PrismaService);
    create(createCoursInput: CreateCoursInput): Promise<{
        id: number;
        createdAt: Date;
        updatedAt: Date;
        nom: string;
        description: string;
        dateDebut: Date;
        dateFin: Date;
        heureDebut: Date;
        heureFin: Date;
        matiereId: number;
        salleId: number;
        classeId: number;
        professeurId: number;
    }>;
    findAll(args: FindManyCoursArgs): Prisma.PrismaPromise<{
        id: number;
        createdAt: Date;
        updatedAt: Date;
        nom: string;
        description: string;
        dateDebut: Date;
        dateFin: Date;
        heureDebut: Date;
        heureFin: Date;
        matiereId: number;
        salleId: number;
        classeId: number;
        professeurId: number;
    }[]>;
    findAllByEtablissement(args: FindManyCoursArgs, etablissementId: number): Prisma.PrismaPromise<{
        id: number;
        createdAt: Date;
        updatedAt: Date;
        nom: string;
        description: string;
        dateDebut: Date;
        dateFin: Date;
        heureDebut: Date;
        heureFin: Date;
        matiereId: number;
        salleId: number;
        classeId: number;
        professeurId: number;
    }[]>;
    findOne(args: FindUniqueCoursArgs): Prisma.Prisma__CoursClient<{
        id: number;
        createdAt: Date;
        updatedAt: Date;
        nom: string;
        description: string;
        dateDebut: Date;
        dateFin: Date;
        heureDebut: Date;
        heureFin: Date;
        matiereId: number;
        salleId: number;
        classeId: number;
        professeurId: number;
    }, null, import("@prisma/client/runtime/library").DefaultArgs>;
    update(updateCoursInput: UpdateCoursInput): Prisma.Prisma__CoursClient<{
        id: number;
        createdAt: Date;
        updatedAt: Date;
        nom: string;
        description: string;
        dateDebut: Date;
        dateFin: Date;
        heureDebut: Date;
        heureFin: Date;
        matiereId: number;
        salleId: number;
        classeId: number;
        professeurId: number;
    }, never, import("@prisma/client/runtime/library").DefaultArgs>;
    remove(args: FindUniqueCoursArgs): Prisma.Prisma__CoursClient<{
        id: number;
        createdAt: Date;
        updatedAt: Date;
        nom: string;
        description: string;
        dateDebut: Date;
        dateFin: Date;
        heureDebut: Date;
        heureFin: Date;
        matiereId: number;
        salleId: number;
        classeId: number;
        professeurId: number;
    }, never, import("@prisma/client/runtime/library").DefaultArgs>;
}
