import { FindManyInscriptionArgs, FindUniqueInscriptionArgs } from './dtos/find.args';
import { PrismaService } from 'src/common/prisma/prisma.service';
import { CreateInscriptionInput } from './dtos/create-inscription.input';
import { UpdateInscriptionInput } from './dtos/update-inscription.input';
import { Prisma } from '@prisma/client';
export declare class InscriptionsService {
    private readonly prisma;
    constructor(prisma: PrismaService);
    create(createInscriptionInput: CreateInscriptionInput): Prisma.Prisma__InscriptionClient<{
        id: number;
        createdAt: Date;
        updatedAt: Date;
        reference: string;
        premiereInscription: boolean;
        dernierDiplome: string;
        autreEtablissement: string;
        activiteProfessionnel: string;
        niveau: string;
        statut: string;
        diplomeId: number;
        etudiantId: number;
        classeId: number;
    }, never, import("@prisma/client/runtime/library").DefaultArgs>;
    findAll(args: FindManyInscriptionArgs): Prisma.PrismaPromise<{
        id: number;
        createdAt: Date;
        updatedAt: Date;
        reference: string;
        premiereInscription: boolean;
        dernierDiplome: string;
        autreEtablissement: string;
        activiteProfessionnel: string;
        niveau: string;
        statut: string;
        diplomeId: number;
        etudiantId: number;
        classeId: number;
    }[]>;
    findAllByEtablissement(args: FindManyInscriptionArgs, id: number): Prisma.PrismaPromise<{
        id: number;
        createdAt: Date;
        updatedAt: Date;
        reference: string;
        premiereInscription: boolean;
        dernierDiplome: string;
        autreEtablissement: string;
        activiteProfessionnel: string;
        niveau: string;
        statut: string;
        diplomeId: number;
        etudiantId: number;
        classeId: number;
    }[]>;
    findOne(args: FindUniqueInscriptionArgs): Prisma.Prisma__InscriptionClient<{
        id: number;
        createdAt: Date;
        updatedAt: Date;
        reference: string;
        premiereInscription: boolean;
        dernierDiplome: string;
        autreEtablissement: string;
        activiteProfessionnel: string;
        niveau: string;
        statut: string;
        diplomeId: number;
        etudiantId: number;
        classeId: number;
    }, null, import("@prisma/client/runtime/library").DefaultArgs>;
    update(updateInscriptionInput: UpdateInscriptionInput): Prisma.Prisma__InscriptionClient<{
        id: number;
        createdAt: Date;
        updatedAt: Date;
        reference: string;
        premiereInscription: boolean;
        dernierDiplome: string;
        autreEtablissement: string;
        activiteProfessionnel: string;
        niveau: string;
        statut: string;
        diplomeId: number;
        etudiantId: number;
        classeId: number;
    }, never, import("@prisma/client/runtime/library").DefaultArgs>;
    remove(args: FindUniqueInscriptionArgs): Prisma.Prisma__InscriptionClient<{
        id: number;
        createdAt: Date;
        updatedAt: Date;
        reference: string;
        premiereInscription: boolean;
        dernierDiplome: string;
        autreEtablissement: string;
        activiteProfessionnel: string;
        niveau: string;
        statut: string;
        diplomeId: number;
        etudiantId: number;
        classeId: number;
    }, never, import("@prisma/client/runtime/library").DefaultArgs>;
}
